import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          baseTheme: [dark],
          card: {
            backgroundColor: "#ffffff",
          },
          formButtonPrimary: {
            fontSize: 14,
            textTransform: "none",
            backgroundColor: "#4bc34b",
            "&:hover, &:focus, &:active": {
              backgroundColor: "green",
            },
          },
        },
      }}
    >
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
