import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import "../globals.css";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      elements: {
        baseTheme: [dark],
        card: {
          backgroundColor: "#222222",
        },
        formButtonPrimary: {
          fontSize: 14,
          textTransform: "none",
          backgroundColor: "#586aea",
          "&:hover, &:focus, &:active": {
            backgroundColor: "#4350ad",
          },
        },
      },
    }}>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
